# Generated by Django 5.0.6 on 2024-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_roledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='referencedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(max_length=200)),
            ],
        ),
    ]
